name: CI (arraybox)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - run: "rustup component add clippy"
    - uses: actions/checkout@v2
    - run: "git submodule init"
    - run: "git submodule update"
    - run: "cargo build --verbose"
      working-directory: arraybox
    - run: "cargo test --verbose --tests"
      working-directory: arraybox
    - run: "cargo test --verbose --doc"
      working-directory: arraybox
    - run: "cargo doc --verbose"
      working-directory: arraybox
    - run: "cargo build --verbose --release"
      working-directory: arraybox
    - name: remove Cargo.lock
      uses: JesseTG/rm@v1.0.3
      with:
        path: arraybox/Cargo.lock
      if: "${{ matrix.os == 'ubuntu-latest' }}"
    - name: remove Cargo.lock
      uses: JesseTG/rm@v1.0.3
      with:
        path: arraybox\Cargo.lock
      if: "${{ matrix.os == 'windows-latest' }}"
    - run: "cargo outdated --verbose --root-deps-only --exit-code 1"
      working-directory: arraybox
    - run: "cargo clippy --verbose"
      working-directory: arraybox
  ensure_no_std:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          triple: x86_64-unknown-linux-gnu
        - os: windows-latest
          triple: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - run: "rustup component add rust-src --toolchain nightly-${{ matrix.triple }}"
    - uses: actions/checkout@v2
    - run: "git submodule init"
    - run: "git submodule update"
    - run: "cargo +nightly build --verbose -Z build-std=core,panic_abort --target ${{ matrix.triple }} --release"
      working-directory: arraybox/ensure_no_std
    - run: "./arraybox/ensure_no_std/target/${{ matrix.triple }}/release/ensure_no_std"
